formatter: markdown table
output:
  file: README.md
  mode: replace
footer-from: "docs/footer.md"

content: |-
  {{ .Header }}

  {{ .Inputs }}

  {{ .Outputs }}  

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Footer }}