formatter: markdown table
output:
  file: README.md
  mode: replace
header-from: "docs/header.md"
footer-from: "docs/footer.md"

content: |-
  {{ .Header }}

  {{ .Inputs }}

  {{ .Outputs }}  

  ## Example

  ```hcl
  {{ include "examples/secured-bucket/main.tf" }}
  ```

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Footer }}